Repository GDG-on-Campus-KNU/GDG_onCampus_KNU_Official_FE, pull requests merged in 2024-11, with the labels that each got.

#157 블로그 마크다운 에디터 구현
  package.json
  pnpm-lock.yaml
  src/apis/hooks/techblog/useGetImage.ts
  src/apis/hooks/techblog/usePostBlog.ts
  src/apis/instance/Api_JWT.ts
  src/assets/thumbnail/uploadthumbnail.svg
  src/components/feature/header/admin/AdminTitle.style.ts
  src/pages/tech_blog/Components/MarkdownEditor.style.ts
  src/pages/tech_blog/Components/MarkdownEditorDark.tsx
  src/pages/tech_blog/Components/MarkdownEditorLight.tsx
  src/pages/tech_blog/Components/TechBlogTitle.tsx
  src/pages/tech_blog/TechBlogEditPage.tsx
  src/pages/tech_blog/TechBlogPostPage.style.ts
  src/pages/tech_blog/TechBlogPostPage.tsx
  src/pages/tech_blog/TechBlogRootPage.tsx
  src/pages/tech_blog/context/index.tsx
  src/pages/tech_blog/hooks/useImageHandler.ts
  src/router/Router.tsx
  src/styles/GlobalStyle.ts
  src/types/UserInterface.ts
Labels: ✨ Feature, 💄 Design

#159 팀 캘린더 커스텀 css 구현 및 공용 컴포넌트 추가 개발
  package.json
  pnpm-lock.yaml
  src/components/common/View/LazyLoad.tsx
  src/components/common/View/LoadingView.tsx
  src/components/common/layouts/grid/index.tsx
  src/components/common/layouts/spacing/index.tsx
  src/pages/team/components/TeamContent.tsx
  src/pages/team/components/blog/TeamBlogList.tsx
  src/pages/team/components/blog/index.tsx
  src/pages/team/components/calendar/Calendar.style.css
  src/pages/team/components/calendar/DateCell.tsx
  src/pages/team/components/calendar/DateNumber.tsx
  src/pages/team/components/calendar/EventContent.tsx
  src/pages/team/components/calendar/Schedule.ts
  src/pages/team/components/calendar/TeamCalendar.tsx
  src/pages/team/components/calendar/index.tsx
  src/pages/team/components/content/TeamContent.tsx
  src/pages/team/components/content/index.tsx
  src/pages/team/components/index.tsx
  src/pages/team/components/member/TeamMember.tsx
  src/pages/team/components/member/index.tsx
  src/pages/team/components/name/TeamName.tsx
  src/pages/team/components/name/index.tsx
  src/pages/team/components/title/TeamTitle.mobile.tsx
  src/pages/team/components/title/TeamTitle.tsx
  src/pages/team/components/title/index.tsx
  src/pages/team/index.tsx
  src/styles/GlobalStyle.ts
Labels: ✨ Feature, 🔧 Chore, 💄 Design

#164 메인 화면 리드미 페이지 독스 기능 업데이트
  README.md
  src/pages/introduce/components/AboutEvent.tsx
  src/pages/introduce/components/CoreTable.tsx
  src/pages/introduce/components/IntroduceEvent.tsx
Labels: 📝 Docs, 🚀 Deploy, ✨ Feature

#169 로고 컨테스트 별 날짜 별로 로고 게시
  src/assets/NavigationLogo.svg
  src/assets/NavigationLogo768.svg
  src/assets/defaultLogo/GDGoC.png
  src/assets/logo_contest/gdgoc_knu_doyeonkim.png
  src/assets/logo_contest/gdgoc_knu_hayeon.png
  src/assets/logo_contest/gdgoc_knu_seojisu.png
  src/assets/logo_contest/gdgocknu_hyunminkim.png
  src/assets/logo_contest/gdgocknu_kimjoohoon.png
  src/assets/logo_contest/gdgocknu_sonheeju.png
  src/assets/logo_contest/gdgocknu_yoonkyuwon.png
  src/components/feature/footer/FooterLink.ts
  src/components/feature/footer/MainFooter.tsx
  src/components/feature/footer/MainFooterMobile.tsx
  src/components/feature/header/MainNavigation.style.ts
  src/components/feature/header/MainNavigation.tsx
  src/components/feature/header/NavLogo.tsx
  src/components/feature/header/NavigationSlideMobile.tsx
  src/components/feature/header/StatusDropDownItems.tsx
  src/components/feature/header/admin/AdminNavigation.tsx
Labels: ✨ Feature, ♻️ Refactoring, 💄 Design

#171 뷰포인트 기반 lazy loading 로직 수정, GA 커스텀 이벤트 등록 및 채용공고 업데이트
  src/components/common/View/LazyLoad.tsx
  src/components/common/title/PageTitle.tsx
  src/hooks/useScrollTracker.ts
  src/pages/apply/ApplyPage.tsx
  src/pages/apply/components/ApplyDocs.ts
  src/pages/apply/components/ApplyEx.tsx
  src/pages/apply/components/ApplyForm.tsx
  src/pages/apply/components/ApplyFormDocs.ts
  src/pages/apply/components/ApplyNavBox.tsx
  src/pages/apply/components/ApplySaveForm.tsx
  src/pages/apply/components/InquiryModal.tsx
  src/pages/community/CommunityPage.tsx
  src/pages/main/components/RotateCarousel.tsx
  src/pages/team/components/blog/TeamBlogList.tsx
  src/pages/team/components/blog/index.tsx
  src/pages/team/components/calendar/DateNumber.tsx
  src/pages/team/components/calendar/Schedule.ts
  src/pages/team/components/calendar/TeamCalendar.tsx
  src/pages/team/components/content/TeamContent.tsx
  src/pages/team/components/index.tsx
  src/pages/team/components/title/TeamTitle.tsx
  src/pages/tech_blog/TechBlogPage.tsx
  src/router/Router.tsx
  src/router/components/MetaData.tsx
  src/router/components/StatusRoute.tsx
  src/styles/ApplyStyle.ts
  src/styles/LayoutStyle.ts
  src/utils/anlytics.ts
  vite.config.ts
Labels: 🐛 BugFix, 📝 Docs, ✨ Feature, 🔧 Chore, 💄 Design
