Repository GDG-on-Campus-KNU/GDG_onCampus_KNU_Official_FE, pull requests merged in 2024-09, with the labels that each got.

#144 어드민페이지 토탈개수 오류수정
  src/apis/hooks/admin/docs/useGetTrack.ts
Labels: 🐛 BugFix

#145 Release-v1.0.11 (#144)
  src/apis/hooks/admin/docs/useGetTrack.ts
Labels: 🐛 BugFix

#147 팀 배치시 팀페이지 내 팀 인원 확인
  src/apis/hooks/team/useGetTeamList.ts
  src/apis/hooks/team/useGetTeamMate.ts
  src/assets/gdgknu.png
  src/assets/gdscknu4/Core-Chaewon.png
  src/assets/gdscknu4/Core-Jeongmin.png
  src/assets/gdscknu4/Core-Yeongin.jpeg
  src/assets/gdscknu4/Core-Yeongin.jpg
  src/components/common/dropdown/index.tsx
  src/components/common/title/PageTitle.tsx
  src/components/feature/auth/AuthModal.tsx
  src/components/feature/footer/MainFooter.tsx
  src/components/feature/footer/MainFooterMobile.tsx
  src/components/feature/header/admin/AdminTitle.tsx
  src/pages/apply/components/ApplyDocs.ts
  src/pages/apply/components/ApplyEx.tsx
  src/pages/apply/components/ApplyForm.tsx
  src/pages/apply/components/ApplyFormDocs.ts
  src/pages/apply/components/ApplyNav.tsx
  src/pages/apply/components/ApplyNavEnd.tsx
  src/pages/apply/components/ApplySaveForm.tsx
  src/pages/introduce/components/CoreTable.tsx
  src/pages/introduce/components/FieldEvent.tsx
  src/pages/introduce/components/IntroduceEvent.tsx
  src/pages/main/components/Content.tsx
  src/pages/main/components/MainIntroduceText.ts
  src/pages/mypage/components/TeamToken.tsx
  src/pages/signin/components/SigninModal.tsx
  src/pages/team/components/TeamContent.tsx
  src/pages/team/components/TeamMember.tsx
  src/pages/team/components/TeamName.tsx
  src/pages/team/components/TeamTitle.tsx
  src/pages/team/components/mobile/TeamTitle.mobile.tsx
  src/pages/team/index.tsx
  src/router/components/MetaData.tsx
  src/styles/ApplyStyle.ts
  src/types/TeamData.type.ts
Labels: ✨ Feature, 👽 API, 💄 Design

#148 Release-v1.1.0
  src/apis/hooks/team/useGetTeamList.ts
  src/apis/hooks/team/useGetTeamMate.ts
  src/assets/gdgknu.png
  src/assets/gdscknu4/Core-Chaewon.png
  src/assets/gdscknu4/Core-Jeongmin.png
  src/assets/gdscknu4/Core-Yeongin.jpeg
  src/assets/gdscknu4/Core-Yeongin.jpg
  src/components/common/dropdown/index.tsx
  src/components/common/title/PageTitle.tsx
  src/components/feature/auth/AuthModal.tsx
  src/components/feature/footer/MainFooter.tsx
  src/components/feature/footer/MainFooterMobile.tsx
  src/components/feature/header/admin/AdminTitle.tsx
  src/pages/apply/components/ApplyDocs.ts
  src/pages/apply/components/ApplyEx.tsx
  src/pages/apply/components/ApplyForm.tsx
  src/pages/apply/components/ApplyFormDocs.ts
  src/pages/apply/components/ApplyNav.tsx
  src/pages/apply/components/ApplyNavEnd.tsx
  src/pages/apply/components/ApplySaveForm.tsx
  src/pages/introduce/components/CoreTable.tsx
  src/pages/introduce/components/FieldEvent.tsx
  src/pages/introduce/components/IntroduceEvent.tsx
  src/pages/main/components/Content.tsx
  src/pages/main/components/MainIntroduceText.ts
  src/pages/mypage/components/TeamToken.tsx
  src/pages/signin/components/SigninModal.tsx
  src/pages/team/components/TeamContent.tsx
  src/pages/team/components/TeamMember.tsx
  src/pages/team/components/TeamName.tsx
  src/pages/team/components/TeamTitle.tsx
  src/pages/team/components/mobile/TeamTitle.mobile.tsx
  src/pages/team/index.tsx
  src/router/components/MetaData.tsx
  src/styles/ApplyStyle.ts
  src/types/TeamData.type.ts
Labels: ✨ Feature
