Repository GDG-on-Campus-KNU/GDG_onCampus_KNU_Official_FE, pull requests merged in 2024-12, with the labels that each got.

#181 프론트엔드, 안드로이드 직렬 추가
  src/pages/apply/components/ApplyDocs.ts
  src/pages/apply/components/ApplyEx.tsx
  src/pages/apply/components/ApplyForm.tsx
  src/pages/apply/components/ApplyFormDocs.ts
  src/pages/apply/components/ApplyNavBox.tsx
  src/pages/apply/components/ApplySaveForm.tsx
Labels: ✨ Feature

#182 직렬 추가 및 공고 게시글 추가
  package.json
  pnpm-lock.yaml
  src/components/common/View/LazyLoad.tsx
  src/pages/apply/components/ApplyDocs.ts
  src/pages/apply/components/ApplyFormDocs.ts
  src/pages/team/components/content/TeamContent.tsx
Labels: 🚀 Deploy, ✨ Feature

#178 어드민페이지 모달창 닫을 때 마크 정보 넘기기 구현
  src/apis/hooks/admin/docs/useGetApplyDocs.ts
  src/apis/hooks/admin/docs/useGetDocsDetail.ts
  src/apis/hooks/admin/docs/usePatchDocsMemo.ts
  src/pages/admin/AdminDocConfirmPage.style.ts
  src/pages/admin/AdminDocConfirmPage.tsx
  src/pages/admin/components/docs/ApplyDetailModal.style.ts
  src/pages/admin/components/docs/ApplyDetailModal.tsx
  src/pages/admin/components/docs/ApplyDetailModalSkeleton.tsx
  src/pages/admin/components/docs/ClassYearIdDropDown.tsx
  src/pages/admin/components/docs/DocsTable.tsx
  src/pages/admin/components/docs/Memo.tsx
Labels: 🐛 BugFix, 💄 Design

#188 feat: 기수 목록 조회 기능 추가
  src/apis/hooks/yearId/useGetClassYearList.ts
  src/pages/admin/components/docs/ClassYearIdDropDown.tsx
Labels: ✨ Feature

#189 기수 목록 조회 기능 추가
  src/apis/hooks/yearId/useGetClassYearList.ts
  src/pages/admin/components/docs/ClassYearIdDropDown.tsx
Labels: ✨ Feature
