Repository GDG-on-Campus-KNU/GDG_onCampus_KNU_Official_FE, pull requests merged in 2024-08, with the labels that each got.

#63 Admin 페이지 헤더 및 사이드바 구현
  index.html
  package.json
  pnpm-lock.yaml
  src/assets/CloseIcon.svg
  src/assets/admin/error.png
  src/components/common/button/CompleteBtn.tsx
  src/components/common/img/LazyLoadingImg.tsx
  src/components/feature/header/MainNavigation.tsx
  src/components/feature/header/MainNavigationMobile.tsx
  src/components/feature/header/admin/AdminNavigation.tsx
  src/components/feature/header/admin/AdminNavigationMobile.tsx
  src/components/feature/header/admin/AdminNavigationSlide.tsx
  src/components/feature/header/admin/AdminSideBar.style.ts
  src/components/feature/header/admin/AdminSideBar.tsx
  src/components/feature/header/admin/AdminTitle.style.ts
  src/components/feature/header/admin/AdminTitle.tsx
  src/components/feature/header/admin/MobileErrorPage.tsx
  src/pages/AdminRootPage.tsx
  src/pages/RootPage.tsx
  src/pages/admin/AdminDocConfirmPage.tsx
  src/pages/admin/AdminSetStatePage.tsx
  src/pages/admin/AdminTeamArrangePage.tsx
  src/pages/admin/components/.keep
  src/pages/admin/index.tsx
  src/pages/apply/components/ApplyDocs.ts
  src/pages/apply/components/ApplyEx.tsx
  src/pages/apply/components/ApplyForm.tsx
  src/pages/apply/components/ApplyFormDocs.ts
  src/router/Router.tsx
  src/styles/GlobalStyle.ts
Labels: ✨ Feature, 💄 Design

#66 상태조정 페이지 구현
  package.json
  pnpm-lock.yaml
  src/apis/hooks/admin/useDeleteUser.ts
  src/apis/hooks/admin/useGetUserList.ts
  src/assets/SearchIcon.svg
  src/assets/admin/trashcanIcon.svg
  src/components/common/button/CommonBtn.tsx
  src/components/common/pagination/pagination.style.ts
  src/components/common/pagination/pagination.tsx
  src/components/feature/header/admin/AdminTitle.tsx
  src/constants/MemberTableColumns.tsx
  src/pages/admin/AdminSetStatePage.style.ts
  src/pages/admin/AdminSetStatePage.tsx
  src/pages/admin/components/.keep
  src/pages/admin/components/status/AdminSearchBar.style.ts
  src/pages/admin/components/status/AdminSearchBar.tsx
  src/pages/admin/components/status/DeleteModal.style.ts
  src/pages/admin/components/status/DeleteModal.tsx
  src/pages/admin/components/status/MemberTable.style.ts
  src/pages/admin/components/status/MemberTable.tsx
  src/pages/admin/components/status/TeamCell.tsx
  src/store/useSelectedUserStore.ts
  src/types/ButtonInterfaces.ts
Labels: ✨ Feature, 👽 API, 💄 Design

#68 Feat/issue #67
  index.html
  package.json
  pnpm-lock.yaml
  public/ WhiteLogo.png
  public/robots.txt
  sitemap.xml
  src/utils/RouterChangeTracker.tsx
Labels: ✨ Feature, 📦 Environment

#70 페이지 별 이동권한 부여
  .gitignore
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/apis/hooks/mypage/useGetMyData.ts
  src/components/feature/header/MainNavigation.tsx
  src/hooks/useColTz.ts
  src/hooks/useDebounce.ts
  src/pages/main/components/RotateCarousel.tsx
  src/provider/auth/index.tsx
  src/router/Router.tsx
  src/router/components/PrivateRoute.tsx
  src/router/components/StatusRoute.tsx
  src/store/useUserStatusStore.ts
  src/types/UserInterface.ts
  src/utils/storage/index.ts
Labels: ✨ Feature, ♻️ Refactoring, 🔥 Remove

#76 상태조정페이지 승인 및 검색기능 구현
  pnpm-lock.yaml
  src/apis/hooks/admin/useApproveUser.ts
  src/apis/hooks/admin/useDeleteUser.ts
  src/apis/hooks/admin/useGetSearchList.ts
  src/pages/admin/AdminSetStatePage.style.tsx
  src/pages/admin/AdminSetStatePage.tsx
  src/pages/admin/components/AdminSearchBar.style.ts
  src/pages/admin/components/AdminSearchBar.tsx
  src/pages/admin/components/MemberTable.style.ts
  src/pages/admin/components/MemberTable.tsx
  src/pages/admin/components/status/ApproveModal.style.ts
  src/pages/admin/components/status/ApproveModal.tsx
Labels: ✨ Feature, 👽 API

#77 서류 상세정보 확인 모달창 구현
  src/apis/hooks/admin/docs/useGetApplyDocs.ts
  src/apis/hooks/admin/docs/useGetDocsDetail.ts
  src/apis/hooks/admin/docs/useGetSearch.ts
  src/apis/hooks/admin/docs/useGetStatistic.ts
  src/apis/hooks/admin/docs/usePatchDocsMemo.ts
  src/apis/hooks/admin/docs/usePatchMark.ts
  src/apis/hooks/admin/docs/usePatchStatus.ts
  src/apis/hooks/admin/status/useDeleteUser.ts
  src/apis/hooks/admin/status/useGetUserList.ts
  src/apis/hooks/admin/usePatchDocsMemo.ts
  src/assets/admin/linkIcon.svg
  src/assets/admin/star.svg
  src/components/common/button/CommonBtn.tsx
  src/pages/admin/AdminDocConfirmPage.tsx
  src/pages/admin/components/MemberTable.style.ts
  src/pages/admin/components/MemberTable.tsx
  src/pages/admin/components/docs/AdminConfirmTable.tsx
  src/pages/admin/components/docs/ApplyDetailModal.style.ts
  src/pages/admin/components/docs/ApplyDetailModal.tsx
  src/pages/admin/components/docs/ApplyInfo.tsx
  src/pages/admin/components/docs/BasicInfo.tsx
  src/pages/admin/components/docs/Memo.tsx
  src/pages/admin/components/docs/Stars.tsx
  src/pages/admin/components/docs/TableSection.tsx
  src/pages/admin/components/docs/TechStack.tsx
  src/pages/admin/components/docs/TrackSelectButtons.tsx
  src/pages/admin/components/status/DeleteModal.tsx
Labels: ✨ Feature, 👽 API, 💄 Design

#78 팀 배치 기능 구현
  .eslintrc.json
  package.json
  pnpm-lock.yaml
  src/apis/hooks/admin/deleteParentTeam.ts
  src/apis/hooks/admin/deleteSubTeam.ts
  src/apis/hooks/admin/postSubTeam.ts
  src/apis/hooks/admin/postTeamToken.ts
  src/apis/hooks/admin/putTeamMember.ts
  src/apis/hooks/admin/useGetAllTeamToken.ts
  src/apis/hooks/admin/useGetTeamMember.ts
  src/apis/instance/Http.ts
  src/assets/admin/PlusBtn.svg
  src/assets/admin/remove.svg
  src/components/common/AsyncBoundary/index.tsx
  src/components/common/Spinner/index.tsx
  src/components/common/View/LoadingView.tsx
  src/components/feature/header/MainNavigation.tsx
  src/components/feature/header/admin/AdminTitle.style.ts
  src/components/feature/header/admin/AdminTitle.tsx
  src/pages/AdminRootPage.tsx
  src/pages/RootPage.tsx
  src/pages/admin/AdminTeamArrangePage.tsx
  src/pages/admin/components/status/MemberTable.style.ts
  src/pages/admin/components/team/CreateTeamToken.style.ts
  src/pages/admin/components/team/CreateTeamToken.tsx
  src/pages/admin/components/team/MemberProfile.tsx
  src/pages/admin/components/team/SubTeamBox.tsx
  src/pages/admin/components/team/TeamBox.style.ts
  src/pages/admin/components/team/TeamBox.tsx
  src/pages/admin/components/team/modal/ButtonContainer.tsx
  src/pages/admin/components/team/modal/CreateTeamModal.tsx
  src/pages/admin/components/team/modal/FormField.tsx
  src/pages/admin/components/team/modal/ModalContent.tsx
  src/pages/admin/components/team/modal/TextContainer.ts
  src/provider/TeamUpdate/index.tsx
  src/router/Router.tsx
  src/router/components/StatusRoute.tsx
  src/styles/GlobalModal.style.ts
  src/styles/GlobalStyle.ts
Labels: 🐛 BugFix, ✨ Feature, 👽 API, 💄 Design

#80 어드민페이지 코드 리팩토링
  src/pages/admin/AdminDocConfirmPage.style.ts
  src/pages/admin/AdminDocConfirmPage.tsx
  src/pages/admin/components/docs/ApplyDetailModal.tsx
  src/pages/admin/components/docs/ApplyDetailModalSkeleton.tsx
  src/pages/admin/components/docs/DocsSearchBar.tsx
Labels: ♻️ Refactoring

#83 refreshToken 발급 구현하기
  src/apis/hooks/admin/docs/useGetApplyDocs.ts
  src/apis/hooks/admin/docs/useGetDocsDetail.ts
  src/apis/hooks/admin/docs/useGetSearch.ts
  src/apis/hooks/admin/docs/useGetStatistic.ts
  src/apis/hooks/admin/docs/usePatchDocsMemo.ts
  src/apis/hooks/admin/docs/usePatchMark.ts
  src/apis/hooks/admin/docs/usePatchStatus.ts
  src/apis/hooks/admin/status/useDeleteUser.ts
  src/apis/hooks/admin/status/useGetUserList.ts
  src/apis/hooks/admin/team/deleteParentTeam.ts
  src/apis/hooks/admin/team/deleteSubTeam.ts
  src/apis/hooks/admin/team/postSubTeam.ts
  src/apis/hooks/admin/team/postTeamToken.ts
  src/apis/hooks/admin/team/putTeamMember.ts
  src/apis/hooks/admin/team/useGetAllTeamToken.ts
  src/apis/hooks/admin/team/useGetTeamMember.ts
  src/apis/hooks/admin/useApproveUser.ts
  src/apis/hooks/admin/useGetSearchList.ts
  src/apis/hooks/mypage/useGetMyData.ts
  src/apis/hooks/signin/ReIssueSigninAPI.ts
  src/apis/instance/Api_JWT.ts
  src/components/feature/header/MainNavigation.tsx
  src/components/feature/header/NavigationSlideMobile.tsx
  src/components/feature/header/StatusDropDownItems.tsx
  src/pages/admin/components/team/CreateTeamToken.tsx
  src/pages/admin/components/team/MemberProfile.tsx
  src/pages/admin/components/team/SubTeamBox.tsx
  src/pages/admin/components/team/TeamBox.tsx
  src/pages/admin/components/team/modal/CreateTeamModal.tsx
  src/pages/apply/components/ApplyDocs.ts
  src/pages/signin/AuthCallBackPage.tsx
  src/router/Router.tsx
  src/types/OAuthInterface.ts
Labels: ✨ Feature, 👽 API

#85 deploy파일 수정
  .github/workflows/deploy.yml
  .gitignore
Labels: 📝 Docs, ✨ Feature, 📦 Environment

#86 Feat: 에러페이지 구현
  src/assets/GDSCLogo.svg
  src/pages/ErrorPage.tsx
Labels: ✨ Feature, 💄 Design

#89 네이버 웹 서치어드바이저 파일 업로드 및 수정
  index.html
  naverf73293df57ba8f81aba3732f06ce5471.html
Labels: 🐛 BugFix, 📦 Environment

#91 서류하기 모달 부분 수정
  src/pages/admin/components/docs/ApplyDetailModal.tsx
Labels: 🐛 BugFix

#95 오픈 그래프 수정
  index.html
  public/ WhiteLogo.png
  public/WhiteLogo.png
  public/favicon.png
Labels: 🐛 BugFix

#97 seo 최적화 및 네이버 서치 어드바이저 적용 하기
  index.html
  naverf73293df57ba8f81aba3732f06ce5471.html
  package.json
  pnpm-lock.yaml
  public/ApplyNav.png
  public/Introduce.png
  public/Login.png
  public/sitemap.xml
  src/main.tsx
  src/pages/MainPage.tsx
  src/pages/apply/ApplyExPage.tsx
  src/pages/apply/ApplyFormPage.tsx
  src/pages/apply/ApplyPage.tsx
  src/pages/introduce/IntroducePage.tsx
  src/pages/main/MainPage.tsx
  src/pages/signin/SigninPage.tsx
  src/styles/GlobalStyle.ts
  src/utils/Seo.tsx
  vite.config.ts
Labels: 🐛 BugFix, 📦 Environment

#101 Release v.1.0.4
  src/pages/introduce/components/FieldTable.tsx
Labels: 💄 Design

#103 8월 19일 버그수정 (1)
  src/pages/admin/components/docs/ApplyDetailModal.style.ts
  src/pages/admin/components/docs/ApplyDetailModal.tsx
  src/pages/apply/components/ApplyDocs.ts
Labels: 🐛 BugFix

#106 렌더링 최적화 및 이미지 최적화
  src/components/common/img/LazyLoadingImg.tsx
  src/pages/admin/AdminDocConfirmPage.tsx
  src/pages/admin/AdminTeamArrangePage.tsx
  src/pages/admin/components/docs/AdminConfirmTable.tsx
  src/pages/admin/components/docs/TableSection.tsx
  src/pages/admin/components/team/CreateTeamToken.tsx
  src/pages/main/MainPage.tsx
  src/pages/main/components/MainRound.tsx
  src/pages/main/components/PCRotateCarousel.tsx
  src/pages/main/components/RotateCarousel.style.ts
  src/pages/main/components/RotateCarousel.tsx
  src/pages/main/components/Tablet/TabletRotateCarousel.tsx
  src/router/Router.tsx
Labels: ✨ Feature, ♻️ Refactoring, 💄 Design

#108 Feat/issue #107
  src/apis/hooks/apply/ApplyInquiryAPI.ts
  src/components/common/button/CommonBtn.tsx
  src/components/feature/header/NavigationSlideMobile.tsx
  src/pages/ErrorPage.tsx
  src/pages/apply/components/InquiryModal.tsx
  src/pages/main/components/Content.tsx
  src/types/ErrorInterface.ts
Labels: 🐛 BugFix, ✨ Feature, 🚑 !HOTFIX, ♻️ Refactoring

#113 comming soon 화면 제작
  src/components/feature/header/MainNavigation.tsx
  src/components/feature/header/MainNavigationMobile.tsx
  src/components/feature/header/NavigationSlideMobile.style.ts
  src/components/feature/header/NavigationSlideMobile.tsx
  src/components/feature/header/StatusDropDownItems.tsx
  src/pages/CommingSoonPage.tsx
  src/pages/RootPage.tsx
  src/pages/apply/components/ApplyNavBox.tsx
  src/router/Router.tsx
Labels: 🐛 BugFix, ✨ Feature, ♻️ Refactoring, 💄 Design

#114 지원 서류 modal 직렬별 질문-답변란 수정
  src/pages/admin/components/docs/AdminConfirmTable.tsx
  src/pages/admin/components/docs/ApplyDetailModal.tsx
Labels: 🐛 BugFix

#115 Fix/issue #111 : Instagram, Kakao In App Browser 에서 구글 OAuth 가 동작하지 않는 버그 픽스
  .babelrc
  .github/workflows/ci.yml
  .gitignore
  jest.config.ts
  package.json
  pnpm-lock.yaml
  src/constants/regex.ts
  src/pages/signin/SigninPage.tsx
  src/utils/__test__/detectUserAgent.test.ts
  src/utils/__test__/urlWithoutProtocol.test.ts
  src/utils/detectUserAgent.ts
  src/utils/openLinkInExternalBrowser.ts
  src/utils/urlWithoutProtocol.ts
  tsconfig.json
Labels: 🐛 BugFix, 🚀 Deploy, ✅ TestCode

#120 메인 페이지 대용량 Gif 네트워크 용량 절약 및 LCP 개선
  src/assets/Earth.webm
  src/pages/main/components/PCRotateCarousel.tsx
  src/pages/main/components/RotateCarousel.style.ts
  src/pages/main/components/Tablet/TabletRotateCarousel.tsx
Labels: 🐛 BugFix

#121 모바일 화면 최적화 로딩
  src/components/common/typography/Text.tsx
  src/pages/main/MainPage.tsx
  src/pages/main/components/PCRotateCarousel.tsx
  src/pages/main/components/RotateCarousel.tsx
  src/pages/main/components/Tablet/TabletRotateCarousel.tsx
Labels: ✨ Feature, ♻️ Refactoring, 💄 Design

#123 임시저장후 조회한뒤 다시 제출하면 saved되는 버그 픽스
  src/pages/apply/components/ApplySaveForm.tsx
Labels: 🐛 BugFix

#126 서류 확인 페이지 Pagination 기능 수정
  src/pages/admin/components/docs/AdminConfirmTable.tsx
Labels: 🐛 BugFix

#127 Release v1.0.7
  src/assets/Earth.webm
  src/components/common/typography/Text.tsx
  src/pages/admin/components/docs/AdminConfirmTable.tsx
  src/pages/main/MainPage.tsx
  src/pages/main/components/PCRotateCarousel.tsx
  src/pages/main/components/RotateCarousel.style.ts
  src/pages/main/components/RotateCarousel.tsx
  src/pages/main/components/Tablet/TabletRotateCarousel.tsx
Labels: 🐛 BugFix, ♻️ Refactoring, 🔧 Chore

#128 어드민 서류확인페이지 오류 수정 및 검색창 기능 수정
  src/apis/hooks/admin/docs/useGetSearch.ts
  src/apis/hooks/admin/docs/useGetTrack.ts
  src/assets/admin/miniStar.svg
  src/constants/DocsTableColumns.tsx
  src/pages/admin/AdminDocConfirmPage.tsx
  src/pages/admin/components/AdminSearchBar.style.ts
  src/pages/admin/components/AdminSearchBar.tsx
  src/pages/admin/components/docs/AdminTableDocs.tsx
  src/pages/admin/components/docs/DocsTable.tsx
  src/pages/admin/components/docs/TableSection.tsx
  src/pages/admin/components/docs/TrackSelectBar.style.ts
  src/pages/admin/components/docs/TrackSelectBar.tsx
  src/pages/admin/components/docs/TrackSelectButtons.tsx
Labels: 🐛 BugFix, ✨ Feature, 👽 API, 💄 Design

#129 Release v1.0.8
  src/apis/hooks/admin/docs/useGetSearch.ts
  src/apis/hooks/admin/docs/useGetTrack.ts
  src/assets/admin/miniStar.svg
  src/constants/DocsTableColumns.tsx
  src/pages/admin/AdminDocConfirmPage.tsx
  src/pages/admin/components/AdminSearchBar.style.ts
  src/pages/admin/components/AdminSearchBar.tsx
  src/pages/admin/components/docs/AdminTableDocs.tsx
  src/pages/admin/components/docs/DocsTable.tsx
  src/pages/admin/components/docs/TableSection.tsx
  src/pages/admin/components/docs/TrackSelectBar.style.ts
  src/pages/admin/components/docs/TrackSelectBar.tsx
  src/pages/admin/components/docs/TrackSelectButtons.tsx
  src/pages/main/components/Tablet/TabletRotateCarousel.tsx
Labels: 🐛 BugFix, ✨ Feature

#131 오픈 그래프 이슈 해결
  .eslintignore
  .eslintrc.json
  .github/workflows/deploy.yml
  index.html
  public/ApplyInquiry.png
  public/CommingSoon.png
  src/apis/hooks/apply/ApplyInquiryAPI.ts
  src/components/feature/auth/AuthModal.tsx
  src/hooks/useScrollTracker.ts
  src/main.tsx
  src/pages/CommingSoonPage.tsx
  src/pages/apply/ApplyExPage.tsx
  src/pages/apply/ApplyFormPage.tsx
  src/pages/apply/ApplyPage.tsx
  src/pages/apply/components/ApplyForm.tsx
  src/pages/apply/components/ApplySaveForm.tsx
  src/pages/community/CommunityPage.tsx
  src/pages/introduce/IntroducePage.tsx
  src/pages/main/MainPage.tsx
  src/pages/main/components/RotateCarousel.style.ts
  src/pages/mypage/MyPage.tsx
  src/pages/signin/SigninPage.tsx
  src/pages/signup/SignupPendingPage.tsx
  src/pages/team/index.tsx
  src/pages/tech_blog/TechBlogPage.tsx
  src/router/Router.tsx
  src/router/components/MetaData.tsx
  src/router/components/RouteChangeTracker.ts
  src/router/components/Seo.tsx
  src/utils/anlytics.ts
  vite.config.ts
Labels: 🐛 BugFix, 🚀 Deploy, ✨ Feature, 📦 Environment, ♻️ Refactoring, 🔧 Chore

#133 Release v1.0.9
  .eslintignore
  .eslintrc.json
  .github/workflows/deploy.yml
  index.html
  public/ApplyInquiry.png
  public/CommingSoon.png
  src/apis/hooks/apply/ApplyInquiryAPI.ts
  src/components/feature/auth/AuthModal.tsx
  src/hooks/useScrollTracker.ts
  src/pages/CommingSoonPage.tsx
  src/pages/apply/ApplyExPage.tsx
  src/pages/apply/ApplyFormPage.tsx
  src/pages/apply/ApplyPage.tsx
  src/pages/apply/components/ApplyForm.tsx
  src/pages/apply/components/ApplySaveForm.tsx
  src/pages/community/CommunityPage.tsx
  src/pages/introduce/IntroducePage.tsx
  src/pages/main/MainPage.tsx
  src/pages/main/components/RotateCarousel.style.ts
  src/pages/mypage/MyPage.tsx
  src/pages/signin/SigninPage.tsx
  src/pages/signup/SignupPendingPage.tsx
  src/pages/team/index.tsx
  src/pages/tech_blog/TechBlogPage.tsx
  src/router/Router.tsx
  src/router/components/MetaData.tsx
  src/router/components/RouteChangeTracker.ts
  src/router/components/Seo.tsx
  src/utils/anlytics.ts
  vite.config.ts
Labels: 🐛 BugFix, 🚀 Deploy, ✨ Feature

#136 기술스텍 부분 좌우 스크롤 추가
  src/pages/admin/components/docs/TechStack.tsx
Labels: 💄 Design

#138 MS 폰트 적용 및 GA 미적용 이슈
  src/components/feature/header/MainNavigation.tsx
  src/pages/apply/components/ApplyNavBox.tsx
  src/styles/GlobalStyle.ts
Labels: 🐛 BugFix

#139 Release v1.0.10
  src/components/feature/header/MainNavigation.tsx
  src/constants/DocsTableColumns.tsx
  src/pages/admin/components/docs/TechStack.tsx
  src/pages/apply/components/ApplyNavBox.tsx
  src/styles/GlobalStyle.ts
Labels: 🐛 BugFix

#140 Fix: 파일 경로 수정
  src/constants/DocsTableColumns.tsx
Labels: 🐛 BugFix
