Repository GDG-on-Campus-KNU/GDG_onCampus_KNU_Official_FE, pull requests merged in 2024-04, with the labels that each got.

#4 추가 개발 환경 세팅
  .github/PULL_REQUEST_TEMPLATE.md
  index.html
  public/GDSC.svg
  src/App.css
  src/App.tsx
  src/api/.gitkeep
  src/components/.gitkeep
  src/constants/.gitkeep
  src/hooks/.gitkeep
  src/interface/.gitkeep
  src/pages/MainPage.tsx
  src/store/.gitkeep
  src/styles/GlobalStyle.ts
  src/styles/README.md
  src/utils/.gitkeep
  src/utils/README.md
Labels: 🐛 BugFix, 📝 Docs, ✨ Feature, 📦 Environment

#5 추가 개발환경 세팅 마무리 - version 1
  .github/PULL_REQUEST_TEMPLATE.md
  index.html
  public/GDSC.svg
  src/App.css
  src/App.tsx
  src/api/.gitkeep
  src/components/.gitkeep
  src/constants/.gitkeep
  src/hooks/.gitkeep
  src/interface/.gitkeep
  src/pages/MainPage.tsx
  src/store/.gitkeep
  src/styles/GlobalStyle.ts
  src/styles/README.md
  src/utils/.gitkeep
  src/utils/README.md
Labels: 📝 Docs, 📦 Environment, 🔧 Chore

#15 로그인/회원가입 개별 컴포넌트 구현
  src/assets/SigninLogo.svg
  src/components/.gitkeep
  src/components/Button/CompleteBtn.tsx
  src/components/Button/SigninBtn.tsx
  src/components/Form/SignupInput.tsx
  src/components/Typography/Text.tsx
  src/components/Typography/Title.tsx
  src/components/auth/SigninModal.tsx
  src/components/auth/SignupCompleteModal.tsx
  src/components/auth/SignupInputModal.tsx
  src/components/auth/SignupModal.tsx
  src/components/common/AuthModal.tsx
  src/components/common/README.md
  src/pages/SigninPage.tsx
  src/pages/SignupPage.tsx
  src/styles/GlobalStyle.ts
  src/styles/LayoutStyle.ts
Labels: ♻️ Refactoring, 💄 Design

#9 회원가입 기능 구현하기
  .prettierrc.json
  package.json
  pnpm-lock.yaml
  public/vite.svg
  src/App.tsx
  src/api/.gitkeep
  src/apis/Api_JWT.ts
  src/apis/signup/SignupAPI.ts
  src/constants/URI.ts
  src/hooks/.gitkeep
  src/hooks/custom_hooks/useDebounce.tsx
  src/hooks/queries/Http.ts
  src/hooks/queries/post/SignupQuery.ts
  src/interface/.gitkeep
  src/interface/UserInterface.ts
  src/main.tsx
  src/pages/SignupPage.tsx
  src/pages/signup/SignupPage.tsx
  src/pages/signup/SignupPendingPage.tsx
  src/pages/signup/components/SignUpForm.tsx
  src/store/.gitkeep
  src/styles/GlobalStyle.ts
  src/utils/.gitkeep
  src/utils/SignUpSchemaUtil.ts
Labels: ✨ Feature, 👽 API, 🔧 Chore

#11 헤더 기능 구현하기
  src/App.css
  src/App.tsx
  src/Router.tsx
  src/components/common/MainNavigation.tsx
  src/components/ui/.gitkeep
  src/pages/RootPage.tsx
  src/pages/apply/ApplyPage.tsx
  src/pages/community/CommunityPage.tsx
  src/pages/introduce/IntroducePage.tsx
  src/pages/logout/Logout.ts
  src/pages/signin/AuthCallBackPage.tsx
  src/pages/tech_blog/TechBlogPage.tsx
  src/styles/GlobalStyle.ts
Labels: ✨ Feature, 👽 API, ♻️ Refactoring, 🔧 Chore
