Repository GDG-on-Campus-KNU/GDG_onCampus_KNU_Official_FE, pull requests merged in 2024-07, with the labels that each got.

#37 Style: 지원서 조회 모달창 퍼블리싱
  src/Router.tsx
  src/components/button/CommonBtn.tsx
  src/components/button/CompleteBtn.tsx
  src/components/form/Input.tsx
  src/interface/ButtonInterfaces.ts
  src/pages/apply/InquiryPage.tsx
  src/pages/apply/components/InquiryModal.tsx
  src/styles/AuthModalStyle.ts
Labels: 💄 Design

#38 지원하기 세부 페이지 구현하기
  src/Router.tsx
  src/apis/signin/SigninGoogleAPI.ts
  src/apis/signup/SignupAPI.ts
  src/assets/ApplyArrow.svg
  src/assets/ApplyForm.svg
  src/assets/ApplyInterview.svg
  src/assets/ApplyResult.svg
  src/components/button/CommonBtn.tsx
  src/hooks/queries/post/SigninQuery.ts
  src/interface/ApplyInterface.ts
  src/interface/OAuthInterface.ts
  src/pages/apply/ApplyExPage.tsx
  src/pages/apply/ApplyFormPage.tsx
  src/pages/apply/components/ApplyDocs.ts
  src/pages/apply/components/ApplyEx.tsx
  src/pages/apply/components/ApplyQualify.tsx
  src/pages/apply/components/PCApplyBox.tsx
  src/pages/signin/AuthCallBackPage.tsx
Labels: ✨ Feature, 💄 Design

#41 Style: 버튼 세부 디자인 수정
  src/components/button/CommonBtn.tsx
  src/components/button/CompleteBtn.tsx
  src/components/button/MobileBtn.tsx
  src/styles/GlobalStyle.ts
Labels: 💄 Design

#46 지원서 로직 수정
  src/pages/apply/components/ApplyForm.style.ts
  src/pages/apply/components/ApplyForm.tsx
  src/pages/apply/components/ApplySaveForm.tsx
  src/types/ApplyInterface.ts
  src/utils/ApplyFormScehma.util.ts
Labels: 🐛 BugFix, 💄 Design

#43 Style: 로그인/회원가입 모달창 구현
  src/assets/HomeIcon.svg
  src/components/auth/AuthModal.tsx
  src/components/button/CommonBtn.tsx
  src/components/button/SigninBtn.tsx
  src/components/form/Input.tsx
  src/components/form/SignupInput.tsx
  src/components/typography/Text.tsx
  src/pages/signin/components/SigninModal.tsx
  src/pages/signup/SignupPendingPage.tsx
  src/pages/signup/components/MobileSignUpForm.tsx
  src/pages/signup/components/SignUpForm.tsx
  src/router/Router.tsx
  src/styles/AuthModalStyle.ts
  src/styles/SignUpForm.style.ts
  src/types/UserInterface.ts
  src/utils/SignUpSchema.util.ts
Labels: 💄 Design

#51 모바일 드롭 다운 버튼 구현 및 전역 상태 구현
  src/components/feature/header/MainNavigation.tsx
  src/components/feature/header/NavigationSlideMobile.tsx
  src/components/feature/header/StatusDropDownItems.tsx
  src/pages/mypage/MyPage.tsx
  src/store/useHeaderDropDownStore.ts
Labels: ✨ Feature, ♻️ Refactoring, 🔧 Chore, 💄 Design

#53 모바일 헤더 이름 및 드롭다운 박스 구현 기타 자잘한 수정
  src/assets/gdscknu4/Core-Bosung.jpg
  src/assets/gdscknu4/Core-Dongpil.jpg
  src/assets/gdscknu4/Core-Gangmin.jpeg
  src/assets/gdscknu4/Core-Hyeonmin.jpeg
  src/assets/gdscknu4/Core-Jaeyong.jpg
  src/assets/gdscknu4/Core-Suhyeon.jpg
  src/assets/gdscknu4/Core-Yeongin.jpg
  src/assets/gdscknu4/Lead-Kyuhoi.png
  src/components/feature/auth/AuthModal.tsx
  src/components/feature/header/MainNavigation.tsx
  src/components/feature/header/NavigationSlideMobile.tsx
  src/pages/apply/ApplyPage.tsx
  src/pages/apply/components/InquiryModal.tsx
  src/pages/introduce/components/CoreTable.tsx
  src/pages/signup/SignupPage.tsx
  src/pages/signup/SignupPendingPage.tsx
  src/pages/signup/components/SignUpForm.tsx
  src/router/Router.tsx
Labels: 🐛 BugFix, ✨ Feature, ♻️ Refactoring, 💄 Design

#57 Profile 이미지가 없을 경우 default 이미지 변경
  src/assets/NoneProfile.png
  src/components/feature/header/MainNavigation.tsx
  src/components/feature/header/StatusDropDownItems.tsx
Labels: 🐛 BugFix

#55 마이페이지 사용자 정보 조회 및 수정 기능 구현
  src/pages/mypage/MyPage.tsx
  src/pages/mypage/hooks/useUserInfo.tsx
  src/styles/GlobalStyle.ts
Labels: ✨ Feature, 💄 Design

#61 QA 1차 수정 PR
  src/apis/hooks/mypage/useGetMyData.ts
  src/components/feature/footer/MainFooter.tsx
  src/pages/apply/components/ApplyForm.tsx
  src/pages/apply/components/ApplyQualify.tsx
  src/pages/apply/components/ApplySaveForm.tsx
  src/styles/GlobalStyle.ts
Labels: 🐛 BugFix, 👽 API

#59 Fix: 마이페이지 자기소개 등록 및 수정, 조회 기능 구현
  src/apis/hooks/mypage/usePutMyData.ts
  src/apis/hooks/mypage/useUserInfo.tsx
  src/components/common/form/TextArea.tsx
  src/pages/mypage/MyPage.tsx
  src/pages/mypage/components/TeamToken.tsx
  src/types/UserInterface.ts
Labels: 🐛 BugFix
