Repository GDG-on-Campus-KNU/GDG_onCampus_KNU_Official_FE, pull requests merged in 2024-05, with the labels that each got.

#20 컴포넌트 하위 폴더명 수정 및 라우터 경로 수정
  src/Router.tsx
  src/components/Button/SigninBtn.tsx
  src/components/Typography/Title.tsx
  src/components/auth/AuthModal.tsx
  src/pages/signin/components/SigninModal.tsx
  src/pages/signup/SignupPendingPage.tsx
  src/pages/signup/components/SignUpForm.tsx
Labels: 🐛 BugFix

#22 푸터 최종 구현
  .babelrc
  package.json
  pnpm-lock.yaml
  src/assets/CompanyLogo.svg
  src/assets/GithubLogo.svg
  src/assets/InstagramLogo.svg
  src/assets/Phone.svg
  src/components/common/MainFooter.tsx
  src/components/common/MainFooterMobile.tsx
  src/components/typography/Text.tsx
  src/pages/MainPage.tsx
  src/styles/FooterLayoutStyle.ts
Labels: ✨ Feature, 💄 Design

#29 동아리 소개 페이지 만들기
  package.json
  pnpm-lock.yaml
  src/components/common/footer/MainFooter.tsx
  src/components/common/footer/MainFooterMobile.tsx
  src/components/common/header/MainNavigation.tsx
  src/components/common/header/MainNavigationMobile.tsx
  src/components/typography/Text.tsx
  src/components/ui/.gitkeep
  src/pages/MainPage.tsx
  src/pages/RootPage.tsx
  src/pages/introduce/IntroducePage.tsx
  src/pages/introduce/components/AboutEvent.tsx
  src/pages/introduce/components/CoreTable.tsx
  src/pages/introduce/components/Diagonal.tsx
  src/pages/introduce/components/FieldEvent.tsx
  src/pages/introduce/components/FieldTable.tsx
  src/pages/introduce/components/IntroduceEvent.tsx
  src/pages/introduce/components/LineEvent.tsx
  src/styles/GlobalStyle.ts
  src/styles/IntroduceStyle.ts
  src/styles/LayoutStyle.ts
Labels: ✨ Feature, 🔥 Remove, 💄 Design

#31 마이페이지 구현
  src/assets/DefaultProfile.svg
  src/assets/EditIcon.svg
  src/components/button/CompleteBtn.tsx
  src/components/form/Input.tsx
  src/components/form/Profile.tsx
  src/components/form/SignupInput.tsx
  src/components/form/TextArea.tsx
  src/components/title/PageTitle.tsx
  src/pages/MyPage.tsx
  src/pages/RootPage.tsx
  src/pages/mypage/MyPage.tsx
  src/pages/mypage/components/TeamToken.tsx
  src/pages/signup/components/SignUpForm.tsx
  src/styles/GlobalStyle.ts
Labels: 💄 Design
