Repository GDG-on-Campus-KNU/GDG_onCampus_KNU_Official_FE, pull requests merged in 2025-06, with the labels that each got.

#211 feat: 인용문 배경컬러 수정
  src/pages/tech_blog/components/editor/MarkdownEditor.tsx
  src/pages/tech_blog/style/MarkdownEditor.style.ts
Labels: 💄 Design

#214 1차 QA 수정
  src/apis/hooks/techblog/useAddLikeCount.ts
  src/apis/hooks/techblog/useDeleteLikeCount.ts
  src/apis/hooks/techblog/usePostBlog.ts
  src/assets/icon/clicklikes.svg
  src/pages/main/components/MainIntroduceText.ts
  src/pages/main/components/PCRotateCarousel.tsx
  src/pages/main/components/Tablet/TabletRotateCarousel.tsx
  src/pages/tech_blog/TechBlogDetailPage.tsx
  src/pages/tech_blog/TechBlogEditPage.tsx
  src/pages/tech_blog/TechBlogPostPage.tsx
  src/pages/tech_blog/components/blogDetail/CommentList.tsx
  src/pages/tech_blog/style/TechBlogPostPage.style.ts
  src/utils/debounce.ts
Labels: 🐛 BugFix, ✨ Feature

#212 마크다운 에디터 수정
  package.json
  pnpm-lock.yaml
  src/apis/hooks/mypage/useGetMyModifies.ts
  src/apis/hooks/mypage/useGetMySaves.ts
  src/apis/hooks/techblog/useAddLikeCount.ts
  src/apis/hooks/techblog/useDeleteLikeCount.ts
  src/apis/hooks/techblog/usePostBlog.ts
  src/assets/Bold.svg
  src/assets/H1.svg
  src/assets/H2.svg
  src/assets/H3.svg
  src/assets/Italic.svg
  src/assets/code.svg
  src/assets/icon/clicklikes.svg
  src/assets/insertImage.svg
  src/assets/link.svg
  src/assets/quote.svg
  src/assets/strikeThrough.svg
  src/components/feature/header/StatusDropDownItems.tsx
  src/pages/main/components/MainIntroduceText.ts
  src/pages/main/components/PCRotateCarousel.tsx
  src/pages/main/components/Tablet/TabletRotateCarousel.tsx
  src/pages/mypage/MyTechBlogPage.tsx
  src/pages/mypage/MyTempBlogPage.tsx
  src/pages/mypage/components/SavesCard.tsx
  src/pages/mypage/hooks/useInfinityMyData.tsx
  src/pages/tech_blog/TechBlogDetailPage.tsx
  src/pages/tech_blog/TechBlogEditPage.tsx
  src/pages/tech_blog/TechBlogPostPage.tsx
  src/pages/tech_blog/components/blogDetail/CommentList.tsx
  src/pages/tech_blog/components/editor/MarkdownEditor.tsx
  src/pages/tech_blog/components/editor/MarkdownEditorDark.tsx
  src/pages/tech_blog/components/editor/MarkdownEditorLight.tsx
  src/pages/tech_blog/style/MarkdownEditor.style.ts
  src/pages/tech_blog/style/TechBlogPostPage.style.ts
  src/router/Router.tsx
  src/types/UserInterface.ts
  src/utils/debounce.ts
Labels: 🐛 BugFix, ✨ Feature, 💄 Design
